### PR TITLE
There appears to be an arithmetic error in the last test case.

### PR DESCRIPTION
**Pull request by aggreyah**
test_create_spend_chart(self). this test appears to have some arithmetic error. the business category withdrawals is 7.3 % of the total withdrawals. this rounded to nearest ten is 10. the tests appears to assume this is zero.

### CODE REVIEW

**Comment by naomi-lgbt** [comment]
Hey there, 

This pull request appears to have been opened accidentally, so we are going to close it. 

If you are having errors with the code you have written, we encourage you to make a post on our [forum](https://forum.freecodecamp.org). 🙂

**Comment by aggreyah** [comment]
Hey. I think there is a bug in the test file. The last test case. This is the information I am trying to convey maybe my methods are wrong.

**Comment by naomi-lgbt** [comment]
To respond to your concern, the instructions do say:
>The height of each bar should be rounded down to the nearest 10.

7.3% rounded *down* would be 0. 🙂

**Comment by aggreyah** [comment]
Aah I see. I was rounding to the nearest ten not rounding down. My bad sorry!

**Pull request closed without merging**
